# -*- coding: utf-8 -*-
"""23_06_2023_4potok.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gSUF4GMXlOoMRHdFxlr98syy91F1c3Er
"""

# Задача 7
import sqlite3
import pandas as pd


con = sqlite3.connect("Schools.db")
df = pd.DataFrame({'School_Id': [5,6,7],
                   'School_Name': ['Ромашка','Василек','Победитель'],
                   'Place_Count': [300, 300, 300]})
df.to_sql('School', con, if_exists='append', index = False)

df2 = pd.read_sql("SELECT * FROM School", con)
df2.to_excel('task77.xlsx', index = False)

# Задача 8
import sqlite3
import pandas as pd

con = sqlite3.connect("Schools.db")
con2 = sqlite3.connect("Students.db")

df1 = pd.read_sql("SELECT * FROM Students", con2)
df1.to_sql("Students",con, if_exists='append', index = False)

df2 = pd.read_sql("SELECT Students.Student_name, Students.School_Id,School.School_Name FROM Students JOIN School ON Students.School_Id=School.School_Id", con)
df2.to_excel('task8.xlsx', index = False)

# Возня с переименованием
import pandas as pd
import sqlite3

def get_connection():
  connection = sqlite3.connect("teachers.db")
  return connection

def get_teacher_data(school_id):
  con = get_connection()
  query = f'SELECT * FROM Teatcher JOIN School ON Teatcher.School_Id = School.School_Id WHERE School.School_Id = {school_id};'
  teacher_data = pd.read_sql(query, con)
  con.close()
  teacher_data.columns = ('Teatcher_Id','Teatcher_Name','School_Id','Joining_Date','Speciality','Salary','Experience','School_Id2','School_Name','Place_Count')
  teacher_data = teacher_data.drop('School_Id', axis = 1)
  print (teacher_data)


get_teacher_data(1)

# Merge iz pandas
import pandas as pd
import sqlite3

def get_connection():
  connection = sqlite3.connect("teachers.db")
  return connection

def get_teacher():
  con = get_connection()
  query = 'SELECT * FROM Teatcher'
  teacher_data = pd.read_sql(query,con)
  con.close()
  return teacher_data


def get_school():
  con = get_connection()
  query = 'SELECT * FROM School'
  school_data = pd.read_sql(query,con)
  con.close()
  return school_data


df1 = get_teacher()
df2 = get_school()

df3 = df1.merge(df2,left_on='School_Id',right_on='School_Id')
print (df3)
df_test = df3.head(3)
print(df_test)

#for index,row in df3.iterrows():
# print (row[1])

def write_data(val):
  df4 = df3[df3['School_Id'] == val]
  df4.to_excel(f'School_id{val}.xlsx', index = False)

list1 = [1,2,3,4]
for i in list1:
  write_data(i)